spring:
  application:
    name: infli
  profiles:
    active: local
  config:
    import: optional:configserver:http://dukcode.iptime.org:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh